/* ============================================================
   한글 종목명 → Yahoo 티커 사전
   형식: [티커, 한글명, 검색보조어(선택)]
   ※ 연 1~2회 수동 업데이트 항목
   ============================================================ */
var TICKER_DICT = [
  /* ---- 지수 ---- */
  ["^KS11", "코스피", "KOSPI 한국종합주가지수"],
  ["^KQ11", "코스닥", "KOSDAQ"],
  ["^GSPC", "S&P500", "에스앤피 미국"],
  ["^IXIC", "나스닥종합", "NASDAQ"],
  ["^NDX", "나스닥100", "NDX"],
  ["^DJI", "다우존스", "다우 DOW"],
  ["^N225", "니케이225", "일본 닛케이"],
  ["^HSI", "항셍지수", "홍콩"],
  ["^VIX", "VIX 공포지수", "변동성"],

  /* ---- 환율 / 원자재 / 코인 ---- */
  ["KRW=X", "달러/원 환율", "원달러 USDKRW"],
  ["JPYKRW=X", "엔/원 환율", "엔화"],
  ["EURKRW=X", "유로/원 환율", "유로"],
  ["DX-Y.NYB", "달러인덱스", "DXY"],
  ["GLD", "금 ETF (GLD)", "골드 gold"],
  ["DBC", "원자재 ETF (DBC)", "커머디티 상품 원유 곡물"],
  ["GC=F", "금 선물", "gold futures"],
  ["SLV", "은 ETF (SLV)", "실버 silver"],
  ["USO", "원유 ETF (USO)", "오일 유가"],
  /* ---- 코인 (v9.3: 76개 · 세 번째 칸 영어 이름은 수집 때 '다른 코인으로 잘못 받았는지' 확인에 써요) ---- */
  ["BTC-USD", "비트코인", "Bitcoin BTC 코인"],
  ["ETH-USD", "이더리움", "Ethereum ETH"],
  ["XRP-USD", "리플", "XRP 엑스알피"],
  ["SOL-USD", "솔라나", "Solana SOL"],
  ["BNB-USD", "바이낸스코인", "BNB Binance"],
  ["DOGE-USD", "도지코인", "Dogecoin DOGE"],
  ["ADA-USD", "에이다", "Cardano ADA 카르다노"],
  ["TRX-USD", "트론", "TRON TRX"],
  ["LINK-USD", "체인링크", "Chainlink LINK"],
  ["AVAX-USD", "아발란체", "Avalanche AVAX"],
  ["DOT-USD", "폴카닷", "Polkadot DOT"],
  ["LTC-USD", "라이트코인", "Litecoin LTC"],
  ["BCH-USD", "비트코인캐시", "Bitcoin Cash BCH"],
  ["SHIB-USD", "시바이누", "Shiba Inu SHIB"],
  ["XLM-USD", "스텔라루멘", "Stellar XLM"],
  ["HBAR-USD", "헤데라", "Hedera HBAR"],
  ["NEAR-USD", "니어프로토콜", "NEAR Protocol"],
  ["SUI20947-USD", "수이", "Sui SUI"],
  ["TON11419-USD", "톤코인", "Toncoin TON"],
  ["UNI7083-USD", "유니스왑", "Uniswap UNI"],
  ["PEPE24478-USD", "페페", "Pepe PEPE"],
  ["XMR-USD", "모네로", "Monero XMR"],
  ["ETC-USD", "이더리움클래식", "Ethereum Classic ETC"],
  ["ICP-USD", "인터넷컴퓨터", "Internet Computer ICP"],
  ["APT21794-USD", "앱토스", "Aptos APT"],
  ["ARB11841-USD", "아비트럼", "Arbitrum ARB"],
  ["OP-USD", "옵티미즘", "Optimism OP"],
  ["FIL-USD", "파일코인", "Filecoin FIL"],
  ["ATOM-USD", "코스모스", "Cosmos ATOM"],
  ["VET-USD", "비체인", "VeChain VET"],
  ["ALGO-USD", "알고랜드", "Algorand ALGO"],
  ["AAVE-USD", "에이브", "Aave AAVE"],
  ["MKR-USD", "메이커", "Maker MKR"],
  ["INJ-USD", "인젝티브", "Injective INJ"],
  ["RENDER-USD", "렌더", "Render RENDER"],
  ["IMX10603-USD", "이뮤터블", "Immutable IMX"],
  ["STX4847-USD", "스택스", "Stacks STX"],
  ["GRT6719-USD", "더그래프", "The Graph GRT"],
  ["SAND-USD", "샌드박스", "Sandbox SAND"],
  ["MANA-USD", "디센트럴랜드", "Decentraland MANA"],
  ["AXS-USD", "엑시인피니티", "Axie Infinity AXS"],
  ["EGLD-USD", "멀티버스엑스", "MultiversX EGLD"],
  ["THETA-USD", "쎄타토큰", "Theta THETA"],
  ["XTZ-USD", "테조스", "Tezos XTZ"],
  ["EOS-USD", "이오스(볼타)", "EOS Vaulta"],
  ["FLOW-USD", "플로우", "Flow FLOW"],
  ["CHZ-USD", "칠리즈", "Chiliz CHZ"],
  ["KAS-USD", "카스파", "Kaspa KAS"],
  ["SEI-USD", "세이", "Sei SEI"],
  ["TIA22861-USD", "셀레스티아", "Celestia TIA"],
  ["WLD-USD", "월드코인", "Worldcoin WLD"],
  ["BONK-USD", "봉크", "Bonk BONK"],
  ["FLOKI-USD", "플로키", "Floki FLOKI"],
  ["WIF-USD", "도그위프햇", "dogwifhat WIF"],
  ["JUP29210-USD", "주피터", "Jupiter JUP"],
  ["ENA-USD", "에테나", "Ethena ENA"],
  ["ONDO-USD", "온도파이낸스", "Ondo ONDO"],
  ["CRO-USD", "크로노스", "Cronos CRO"],
  ["LEO-USD", "레오", "UNUS SED LEO"],
  ["OKB-USD", "OKB", "OKB"],
  ["QNT-USD", "퀀트", "Quant QNT"],
  ["LDO-USD", "리도다오", "Lido DAO LDO"],
  ["CRV-USD", "커브", "Curve CRV"],
  ["FET-USD", "페치(ASI)", "Fetch.ai Artificial Superintelligence FET"],
  ["NEO-USD", "네오", "NEO"],
  ["ZEC-USD", "지캐시", "Zcash ZEC"],
  ["DASH-USD", "대시", "Dash DASH"],
  ["IOTA-USD", "아이오타", "IOTA"],
  ["KAVA-USD", "카바", "Kava KAVA"],
  ["ENS-USD", "이더리움네임서비스", "Ethereum Name Service ENS"],
  ["BAT-USD", "베이직어텐션토큰", "Basic Attention Token BAT"],
  ["ZIL-USD", "질리카", "Zilliqa ZIL"],
  ["1INCH-USD", "1인치", "1inch"],
  ["GALA-USD", "갈라", "Gala GALA"],
  ["TAO22974-USD", "비트텐서", "Bittensor TAO"],
  ["XDC-USD", "XDC네트워크", "XDC Network"],

  /* ---- 미국 채권 ETF ---- */
  ["TLT", "미국채 20년+ (TLT)", "장기채"],
  ["IEF", "미국채 7-10년 (IEF)", "중기채"],
  ["SHY", "미국채 1-3년 (SHY)", "단기채"],
  ["LQD", "미국 회사채 (LQD)", "투자등급"],

  /* ---- 미국 대표 ETF ---- */
  ["SPY", "S&P500 ETF (SPY)", "스파이"],
  ["VOO", "S&P500 ETF (VOO)", "뱅가드"],
  ["QQQ", "나스닥100 ETF (QQQ)", "큐큐큐"],
  ["VTI", "미국 전체시장 (VTI)", "토탈마켓"],
  ["SCHD", "미국 배당 ETF (SCHD)", "슈드 배당"],
  ["JEPI", "JEPI 커버드콜", "월배당"],
  ["SOXX", "반도체 ETF (SOXX)", "필라델피아"],
  ["SMH", "반도체 ETF (SMH)", "반도체"],
  ["TQQQ", "나스닥100 3배 (TQQQ)", "레버리지"],
  ["SOXL", "반도체 3배 (SOXL)", "레버리지"],
  ["ARKK", "ARKK 혁신 ETF", "아크"],

  /* ---- 한국 ETF ---- */
  ["069500.KS", "KODEX 200", "코덱스"],
  ["360750.KS", "TIGER 미국S&P500", "타이거"],
  ["133690.KS", "TIGER 미국나스닥100", "타이거"],
  ["122630.KS", "KODEX 레버리지", "코덱스"],
  ["114800.KS", "KODEX 인버스", "코덱스"],
  ["132030.KS", "KODEX 골드선물(H)", "금 코덱스"],

  /* ---- 미국 개별주 (한글명) ---- */
  ["NVDA", "엔비디아", "NVIDIA"],
  ["AAPL", "애플", "Apple"],
  ["MSFT", "마이크로소프트", "Microsoft"],
  ["GOOGL", "알파벳A(구글, 의결권)", "Google Alphabet 구글 클래스A"],
  ["GOOG", "알파벳C(구글, 무의결권)", "Google Alphabet 구글 클래스C"],
  ["AMZN", "아마존", "Amazon"],
  ["META", "메타(페이스북)", "Facebook"],
  ["TSLA", "테슬라", "Tesla"],
  ["AVGO", "브로드컴", "Broadcom"],
  ["AMD", "AMD", "에이엠디"],
  ["INTC", "인텔", "Intel"],
  ["MU", "마이크론", "Micron"],
  ["TSM", "TSMC", "대만반도체 티에스엠씨"],
  ["ASML", "ASML", "에이에스엠엘"],
  ["QCOM", "퀄컴", "Qualcomm"],
  ["PLTR", "팔란티어", "Palantir"],
  ["NFLX", "넷플릭스", "Netflix"],
  ["COIN", "코인베이스", "Coinbase"],
  ["MSTR", "마이크로스트래티지", "Strategy"],
  ["BRK-B", "버크셔해서웨이B", "버핏 Berkshire 버크셔 클래스B"],
  ["BRK-A", "버크셔해서웨이A", "버핏 Berkshire 버크셔 클래스A 고가주"],
  ["LLY", "일라이릴리", "Eli Lilly"],
  ["JNJ", "존슨앤존슨", "Johnson"],
  ["V", "비자", "Visa"],
  ["JPM", "JP모건", "제이피모건"],
  ["KO", "코카콜라", "Coca Cola"],
  ["WMT", "월마트", "Walmart"],
  ["DIS", "디즈니", "Disney"],
  ["NKE", "나이키", "Nike"],
  ["SBUX", "스타벅스", "Starbucks"],
  ["BA", "보잉", "Boeing"],
  ["UBER", "우버", "Uber"],
  ["ABNB", "에어비앤비", "Airbnb"],
  ["BABA", "알리바바", "Alibaba"],
  ["SMCI", "슈퍼마이크로", "Supermicro"],

  /* ---- 한국 코스피 ---- */
  ["005930.KS", "삼성전자", "삼전"],
  ["005935.KS", "삼성전자우", "삼전우"],
  ["000660.KS", "SK하이닉스", "하이닉스"],
  ["373220.KS", "LG에너지솔루션", "엘지엔솔"],
  ["207940.KS", "삼성바이오로직스", "삼바"],
  ["005380.KS", "현대차", "현대자동차"],
  ["000270.KS", "기아", "기아차"],
  ["068270.KS", "셀트리온", ""],
  ["005490.KS", "POSCO홀딩스", "포스코"],
  ["035420.KS", "NAVER", "네이버"],
  ["035720.KS", "카카오", ""],
  ["105560.KS", "KB금융", "케이비금융"],
  ["055550.KS", "신한지주", "신한"],
  ["086790.KS", "하나금융지주", "하나금융"],
  ["316140.KS", "우리금융지주", "우리금융"],
  ["138040.KS", "메리츠금융지주", "메리츠"],
  ["051910.KS", "LG화학", "엘지화학"],
  ["006400.KS", "삼성SDI", "삼성에스디아이"],
  ["012330.KS", "현대모비스", "모비스"],
  ["028260.KS", "삼성물산", ""],
  ["032830.KS", "삼성생명", ""],
  ["066570.KS", "LG전자", "엘지전자"],
  ["009150.KS", "삼성전기", ""],
  ["402340.KS", "SK스퀘어", ""],
  ["096770.KS", "SK이노베이션", "에스케이이노베이션"],
  ["017670.KS", "SK텔레콤", "에스케이텔레콤"],
  ["030200.KS", "KT", "케이티"],
  ["033780.KS", "KT&G", "케이티앤지"],
  ["015760.KS", "한국전력", "한전"],
  ["012450.KS", "한화에어로스페이스", "한화에어로 방산"],
  ["079550.KS", "LIG넥스원", "방산"],
  ["047810.KS", "한국항공우주", "KAI 방산"],
  ["064350.KS", "현대로템", "방산"],
  ["042660.KS", "한화오션", "조선"],
  ["009540.KS", "HD한국조선해양", "조선"],
  ["329180.KS", "HD현대중공업", "조선"],
  ["010140.KS", "삼성중공업", "조선"],
  ["034020.KS", "두산에너빌리티", "두산 원전"],
  ["241560.KS", "두산밥캣", "두산"],
  ["352820.KS", "하이브", "HYBE 방탄"],
  ["036570.KS", "엔씨소프트", "엔씨"],
  ["251270.KS", "넷마블", ""],
  ["259960.KS", "크래프톤", "배그"],
  ["323410.KS", "카카오뱅크", "카뱅"],
  ["090430.KS", "아모레퍼시픽", "아모레"],
  ["051900.KS", "LG생활건강", "엘지생건"],
  ["097950.KS", "CJ제일제당", "씨제이"],
  ["003490.KS", "대한항공", ""],
  ["011200.KS", "HMM", "에이치엠엠 해운"],
  ["003670.KS", "포스코퓨처엠", "포스코케미칼"],
  ["042700.KS", "한미반도체", ""],
  ["010130.KS", "고려아연", ""],
  ["000100.KS", "유한양행", ""],
  ["086280.KS", "현대글로비스", "글로비스"],
  ["011170.KS", "롯데케미칼", "롯데"],
  ["010950.KS", "S-Oil", "에스오일"],
  ["078930.KS", "GS", "지에스"],
  ["009830.KS", "한화솔루션", "한화"],
  ["010060.KS", "OCI홀딩스", "오씨아이"],

  /* ---- 한국 코스닥 ---- */
  ["196170.KQ", "알테오젠", "바이오"],
  ["247540.KQ", "에코프로비엠", "에코프로"],
  ["086520.KQ", "에코프로", ""],
  ["028300.KQ", "HLB", "에이치엘비"],
  ["058470.KQ", "리노공업", ""],
  ["068760.KQ", "셀트리온제약", ""],
  ["096530.KQ", "씨젠", ""],
  ["263750.KQ", "펄어비스", "검은사막"],
  ["293490.KQ", "카카오게임즈", ""],
  ["035900.KQ", "JYP Ent.", "제이와이피"],
  ["041510.KQ", "에스엠", "SM엔터"],
  ["122870.KQ", "와이지엔터테인먼트", "YG"],

  /* ---- 미국 개별주 · 에너지 / 산업재 ---- */
  ["XOM", "엑손모빌", "Exxon Mobil 엑슨 정유 석유"],
  ["CVX", "셰브론", "Chevron 정유 석유"],
  ["COP", "코노코필립스", "ConocoPhillips 석유"],
  ["SHEL", "쉘", "Shell 로열더치쉘 석유"],
  ["BP", "BP", "비피 브리티시페트롤리엄 석유"],
  ["SLB", "슐럼버거", "Schlumberger 유전서비스"],
  ["OXY", "옥시덴탈페트롤리엄", "Occidental 옥시 석유"],
  ["GE", "GE에어로스페이스", "제너럴일렉트릭 제네럴일렉트로닉 General Electric GE항공 항공엔진"],
  ["GEHC", "GE헬스케어", "GE HealthCare 지이헬스케어 제너럴일렉트릭 분할 의료기기 영상진단"],
  ["GEV", "GE버노바", "GE Vernova 지이버노바 제너럴일렉트릭 분할 전력 발전 터빈"],
  ["CAT", "캐터필러", "Caterpillar 중장비"],
  ["DE", "디어", "Deere 존디어 농기계"],
  ["HON", "허니웰", "Honeywell"],
  ["MMM", "3M", "쓰리엠 스리엠"],
  ["LMT", "록히드마틴", "Lockheed Martin 방산"],
  ["RTX", "RTX", "레이시온 Raytheon 방산"],
  ["NOC", "노스럽그러먼", "Northrop 방산"],
  ["GD", "제너럴다이내믹스", "General Dynamics 방산"],
  ["UNP", "유니온퍼시픽", "Union Pacific 철도"],
  ["ETN", "이튼", "Eaton 전력장비"],
  ["EMR", "에머슨일렉트릭", "Emerson"],

  /* ---- 미국 개별주 · 금융 ---- */
  ["BAC", "뱅크오브아메리카", "Bank of America 뱅크오브아메리카 BOA"],
  ["WFC", "웰스파고", "Wells Fargo"],
  ["GS", "골드만삭스", "Goldman Sachs"],
  ["MS", "모건스탠리", "Morgan Stanley"],
  ["C", "씨티그룹", "Citigroup 시티"],
  ["BLK", "블랙록", "BlackRock"],
  ["AXP", "아메리칸익스프레스", "American Express 아멕스"],
  ["MA", "마스터카드", "Mastercard"],
  ["SCHW", "찰스슈왑", "Charles Schwab"],
  ["CB", "처브", "Chubb 보험"],

  /* ---- 미국 개별주 · 헬스케어 ---- */
  ["UNH", "유나이티드헬스", "UnitedHealth 보험"],
  ["PFE", "화이자", "Pfizer"],
  ["MRK", "머크", "Merck"],
  ["ABBV", "애브비", "AbbVie"],
  ["ABT", "애보트", "Abbott"],
  ["TMO", "써모피셔", "Thermo Fisher 서모피셔"],
  ["AMGN", "암젠", "Amgen"],
  ["NVO", "노보노디스크", "Novo Nordisk 위고비 비만"],
  ["VRTX", "버텍스파마", "Vertex"],
  ["REGN", "리제네론", "Regeneron"],
  ["ISRG", "인튜이티브서지컬", "Intuitive Surgical 수술로봇"],

  /* ---- 미국 개별주 · 소비재 ---- */
  ["PG", "P&G", "Procter Gamble 프록터앤드갬블 피앤지"],
  ["PEP", "펩시코", "PepsiCo 펩시"],
  ["MCD", "맥도날드", "McDonalds"],
  ["COST", "코스트코", "Costco"],
  ["HD", "홈디포", "Home Depot"],
  ["LOW", "로우스", "Lowes"],
  ["TGT", "타겟", "Target"],
  ["MO", "알트리아", "Altria 담배"],
  ["PM", "필립모리스", "Philip Morris 담배"],
  ["MDLZ", "몬델리즈", "Mondelez 오레오"],
  ["CL", "콜게이트", "Colgate"],
  ["BKNG", "부킹홀딩스", "Booking 부킹닷컴"],
  ["F", "포드", "Ford 포드자동차"],
  ["GM", "제너럴모터스", "General Motors 지엠"],
  ["RIVN", "리비안", "Rivian 전기차"],

  /* ---- 미국 개별주 · 기술 / 통신 ---- */
  ["ORCL", "오라클", "Oracle"],
  ["CRM", "세일즈포스", "Salesforce"],
  ["ADBE", "어도비", "Adobe"],
  ["IBM", "IBM", "아이비엠"],
  ["CSCO", "시스코", "Cisco"],
  ["TXN", "텍사스인스트루먼트", "Texas Instruments 티아이"],
  ["NOW", "서비스나우", "ServiceNow"],
  ["PANW", "팔로알토네트웍스", "Palo Alto 보안"],
  ["CRWD", "크라우드스트라이크", "CrowdStrike 보안"],
  ["SNOW", "스노우플레이크", "Snowflake"],
  ["ARM", "ARM홀딩스", "암홀딩스 반도체설계"],
  ["MRVL", "마벨테크놀로지", "Marvell 반도체"],
  ["LRCX", "램리서치", "Lam Research 반도체장비"],
  ["AMAT", "어플라이드머티어리얼즈", "Applied Materials 반도체장비"],
  ["KLAC", "KLA", "케이엘에이 반도체장비"],
  ["ADI", "아나로그디바이스", "Analog Devices 반도체"],
  ["NXPI", "NXP반도체", "엔엑스피"],
  ["PYPL", "페이팔", "PayPal"],
  ["SHOP", "쇼피파이", "Shopify"],
  ["SPOT", "스포티파이", "Spotify"],
  ["T", "AT&T", "에이티앤티 통신"],
  ["VZ", "버라이즌", "Verizon 통신"],
  ["CMCSA", "컴캐스트", "Comcast"],

  /* ---- 미국 개별주 · 유틸리티 / 소재 / 리츠 ---- */
  ["NEE", "넥스트에라에너지", "NextEra 재생에너지"],
  ["DUK", "듀크에너지", "Duke Energy"],
  ["SO", "서던컴퍼니", "Southern Company"],
  ["LIN", "린데", "Linde 산업가스"],
  ["FCX", "프리포트맥모란", "Freeport 구리"],
  ["NEM", "뉴몬트", "Newmont 금광"],
  ["O", "리얼티인컴", "Realty Income 월배당 리츠"],
  ["PLD", "프로로지스", "Prologis 물류 리츠"],
  ["SPGI", "S&P글로벌", "SP Global"]
];
